;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        comment-dwim
        delete-indentation
        eide-smart-beginning-of-line
        electric-pair-delete-pair
        expand-line-contract-next-line
        expand-line-contract-previous-line
        expand-line-expand-next-line
        expand-line-expand-previous-line
        haml-electric-backspace
        indent-for-tab-command
        mark-whole-buffer
        org-delete-char
        org-end-of-line
        org-meta-return
        org-schedule
        org-self-insert-command
        org-shiftleft
        org-shiftright
        paredit-backward
        paredit-backward-kill-word
        paredit-close-square
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp-killing-backward
        slim-electric-backspace
        turn-on-expand-line-mode
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        eide-mark-word
        ido-find-file
        ido-switch-buffer
        mc/mark-next-like-this-dwim
        mc/mark-previous-like-this-dwim
        mc/skip-to-next-like-this-dwim
        mc/unmark-next-like-this-dwim
        ns-copy-including-secondary
        save-some-buffers
        smex
        ))
